In [1]:
import re
import string
import time
from copy import deepcopy

In [3]:
import pandas as pd
df = pd.read_csv('dataset_komentar_instagram_cyberbullying.csv')
df['Sentiment'] = df['Sentiment'].apply(lambda x: 1 if x == 'positive' else 0)
df.head()

   Id Sentiment                             Instagram Comment Text
0   1  negative   <USERNAME> TOLOL!! Gak ada hubungan nya kegug...
1   2  negative  Geblek lo tata...cowo bgt dibela2in balikan......
2   3  negative  Kmrn termewek2 skr lengket lg duhhh kok labil ...
3   4  negative  Intinya kalau kesel dengan ATT nya, gausah ke ...
4   5  negative  hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Id'].plot(kind='hist', bins=20, title='Id')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('Instagram Comment Text').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='index', y='Id', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_4.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Instagram Comment Text')):
  _plot_series(series, series_name, i)
  fig.legend(title='Instagram Comment Text', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Id']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Id'}, axis=1)
              .sort_values('Id', ascending=True))
  xs = counted['Id']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('Id', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Instagram Comment Text')):
  _plot_series(series, series_name, i)
  fig.legend(title='Instagram Comment Text', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Id')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_6['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7['Id'].plot(kind='line', figsize=(8, 4), title='Id')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_8['Instagram Comment Text'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_8, x='index', y='Instagram Comment Text', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_9['Instagram Comment Text'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_9, x='Id', y='Instagram Comment Text', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [10]:
df['Sentiment'] = df['Sentiment'].replace({'negative': 0, 'positive': 1})
df.head()

   Sentiment                             Instagram Comment Text
0          0   <USERNAME> TOLOL!! Gak ada hubungan nya kegug...
1          0  Geblek lo tata...cowo bgt dibela2in balikan......
2          0  Kmrn termewek2 skr lengket lg duhhh kok labil ...
3          0  Intinya kalau kesel dengan ATT nya, gausah ke ...
4          0  hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...

In [12]:
!pip install ekphrasis

Collecting ekphrasis
  Downloading ekphrasis-0.5.4-py3-none-any.whl.metadata (610 bytes)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from ekphrasis) (3.1.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ekphrasis) (4.67.1)
Collecting colorama (from ekphrasis)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting ujson (from ekphrasis)
  Downloading ujson-5.11.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (9.4 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from ekphrasis) (3.10.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from ekphrasis) (3.9.1)
Collecting ftfy (from ekphrasis)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from ekphrasis) (2.0.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy->ekphrasis) (0.2.14)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->ekphrasis) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->ekphrasis) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->ekphrasis) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->ekphrasis) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->ekphrasis) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->ekphrasis) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->ekphrasis) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->ekphrasis) (2.9.0.post0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->ekphrasis) (8.3.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->ekphrasis) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->ekphrasis) (2024.11.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->ekphrasis) (1.17.0)
Downloading ekphrasis-0.5.4-py3-none-any.whl (83 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.8/83.8 kB 5.0 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.2 MB/s eta 0:00:00
Downloading ujson-5.11.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.4/57.4 kB 3.9 MB/s eta 0:00:00
Installing collected packages: ujson, ftfy, colorama, ekphrasis
Successfully installed colorama-0.4.6 ekphrasis-0.5.4 ftfy-6.3.1 ujson-5.11.0

In [16]:
from ekphrasis.classes.preprocessor import TextPreProcessor
from ekphrasis.classes.tokenizer import SocialTokenizer
from ekphrasis.dicts.emoticons import emoticons

text_processor = TextPreProcessor(
    # terms that will be normalized
    normalize=['email', 'percent', 'money', 'phone', 'user',
        'time', 'date', 'number'],
    # terms that will be annotated
    #annotate={"hashtag", "allcaps", "elongated", "repeated",'emphasis', 'censored'},
    annotate={"hashtag"},
    fix_html=True,  # fix HTML tokens

    # corpus from which the word statistics are going to be used
    # for word segmentation
    segmenter="twitter",

    # corpus from which the word statistics are going to be used
    # for spell correction
    corrector="twitter",

    unpack_hashtags=True,  # perform word segmentation on hashtags
    unpack_contractions=True,  # Unpack contractions (can't -> can not)
    spell_correct_elong=False,  # spell correction for elongated words

    # select a tokenizer. You can use SocialTokenizer, or pass your own
    # the tokenizer, should take as input a string and return a list of tokens
    tokenizer=SocialTokenizer(lowercase=True).tokenize,

    # list of dictionaries, for replacing tokens extracted from the text,
    # with other expressions. You can pass more than one dictionaries.
    dicts=[emoticons]
)

Reading twitter - 1grams ...
Reading twitter - 2grams ...
Reading twitter - 1grams ...

In [17]:
def bersih_data(text):
    return " ".join(text_processor.pre_process_doc(text))

In [21]:
def non_ascii(text):
    return text.encode('ascii', 'replace').decode('ascii')

def remove_space_alzami(text):
    return " ".join(text.split())

def remove_emoji_alzami(text):
    return ' '.join(re.sub("([x#][A-Za-z0-9]+)"," ", text).split())

def remove_tab(text):
    return text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")

def remove_tab2(text):
    return re.sub(r'\s+',' ',text)

def remove_rt(text):
    return text.replace('RT'," ")

def remove_mention(text):
    return ' '.join(re.sub(r'([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)', ' ', text).split())

def remove_incomplete_url(text):
    return text.replace("http://", " ").replace("https://", " ")

def remove_single_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

def remove_excessive_dot(text):
    return text.replace('..'," ")

def change_stripe(text):
    return text.replace('-'," ")

def lower(text):
    return text.lower()

def remove_single_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

def remove_excessive_dot(text):
    return text.replace('..'," ")

def lower(text):
    return text.lower()

def remove_whitespace_LT(text):
    return text.strip()

def remove_whitespace_multiple(text):
    return re.sub(r'\s+', ' ', text)

def remove_punctuation(text):
    remove = string.punctuation
    remove = remove.replace("_", "") # don't remove hyphens
    pattern = r"[{}]".format(remove) # create the pattern
    return re.sub(pattern, "", text)

In [22]:
def remove_number_eks(text):
    return text.replace('<number>'," ")

def remove_angka(text):
    return re.sub(r"\d+", "", text)

def remove_URL_eks(text):
    return text.replace('URL'," ").replace('url'," ")

def space_punctuation(text):
    return re.sub('(?<! )(?=[.,!?()])|(?<=[.,!?()])(?! )', r' ', text)

In [24]:
i = 0
final_string = []
s = ""
for text in df['Instagram Comment Text'].values:
    filteredSentence = []
    EachReviewText = ""
    proc = remove_rt(text)
    proc = lower(proc)
    proc = change_stripe(proc)
    proc = remove_emoji_alzami(proc)
    proc = remove_tab(proc)
    proc = remove_tab2(proc)
    proc = non_ascii(proc)
    proc = remove_incomplete_url(proc)
    proc = remove_excessive_dot(proc)
    proc = remove_whitespace_LT(proc)
    proc = remove_whitespace_multiple(proc)
    proc = remove_single_char(proc)
    proc = space_punctuation(proc)
    proc = remove_punctuation(proc)
    proc = remove_space_alzami(proc)
    proc = bersih_data(proc)
    proc = remove_number_eks(proc)
    proc = remove_angka(proc)
    proc = remove_URL_eks(proc)
    EachReviewText = proc
    final_string.append(EachReviewText)

In [25]:
df["step01"] = final_string

In [26]:
df.head(10)

,Sentiment,Instagram Comment Text,step01
0,0,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...
1,0,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tata cowo bgt dibelain balikan hadew...
2,0,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...
3,0,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...
4,0,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lg sakit jiwa knp harus...
5,0,"Pantesan di tinggalin laki, ya lakinya juga mi...",pantesan di tinggalin laki ya lakinya juga mik...
6,0,kebiasaan balajaer nyampah d ig para artis..su...,kebiasaan balajaer nyampah ig para artis suka ...
7,0,krn sebagian besar rakyat indonesia itu bodoh....,krn sebagian besar rakyat indonesia itu bodoh ...
8,0,ayu janda bego pny suami kpn nikah laginya?,ayu janda bego pny suami kpn nikah laginya
9,0,"Anyiennnnggg.. Suaranya ancur banget, lebih me...",anyiennnnggg suaranya ancur banget lebih merdu...

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sentiment               400 non-null    int64
 1   Instagram Comment Text  400 non-null    object
 2   step01                  400 non-null    object
dtypes: int64(1), object(2)
memory usage: 9.5+ KB

In [28]:
df_hapus = df[~df['step01'].str.contains(" ")]

In [29]:
df_hapus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sentiment               0 non-null      int64
 1   Instagram Comment Text  0 non-null      object
 2   step01                  0 non-null      object
dtypes: int64(1), object(2)
memory usage: 0.0+ bytes

In [30]:
df_hapus.head(10)

Empty DataFrame
Columns: [Sentiment, Instagram Comment Text, step01]
Index: []

In [31]:
df_new = df[~df.isin(df_hapus)].dropna()

In [32]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sentiment               400 non-null    int64
 1   Instagram Comment Text  400 non-null    object
 2   step01                  400 non-null    object
dtypes: int64(1), object(2)
memory usage: 9.5+ KB

In [33]:
df_new

,Sentiment,Instagram Comment Text,step01
0,0,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...
1,0,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tata cowo bgt dibelain balikan hadew...
2,0,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...
3,0,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...
4,0,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lg sakit jiwa knp harus...
...,...,...,...
395,1,Bangga sama suami yg selalu ingat istri disela...,bangga sama suami yg selalu ingat istri disela...
396,1,Apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg penting halal tuk menaf...
397,1,Gojek itu mayoritas pegangguran yang lama gak ...,gojek itu mayoritas pegangguran yang lama gak ...
398,1,<USERNAME> aslinya cantik dan ayu loh mbak kr...,username aslinya cantik dan ayu loh mbak krn a...
399,1,"<USERNAME> suami saya seumuran sama saya mba,...",username suami saya seumuran sama saya mba mal...

In [37]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [38]:
def word_tokenize_wrapper(text):
  return word_tokenize(text)

In [39]:
df_new['tokens'] = df['step01'].apply(word_tokenize_wrapper)

In [40]:
df_new.head(10)

,Sentiment,Instagram Comment Text,step01,tokens
0,0,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...,"[username, tolol, gak, ada, hubungan, nya, keg..."
1,0,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tata cowo bgt dibelain balikan hadew...,"[geblek, lo, tata, cowo, bgt, dibelain, balika..."
2,0,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...,"[kmrn, termewek, skr, lengket, lg, duhhh, kok,..."
3,0,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...,"[intinya, kalau, kesel, dengan, att, nya, gaus..."
4,0,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lg sakit jiwa knp harus...,"[hadewwwww, permpuan, itu, lg, sakit, jiwa, kn..."
5,0,"Pantesan di tinggalin laki, ya lakinya juga mi...",pantesan di tinggalin laki ya lakinya juga mik...,"[pantesan, di, tinggalin, laki, ya, lakinya, j..."
6,0,kebiasaan balajaer nyampah d ig para artis..su...,kebiasaan balajaer nyampah ig para artis suka ...,"[kebiasaan, balajaer, nyampah, ig, para, artis..."
7,0,krn sebagian besar rakyat indonesia itu bodoh....,krn sebagian besar rakyat indonesia itu bodoh ...,"[krn, sebagian, besar, rakyat, indonesia, itu,..."
8,0,ayu janda bego pny suami kpn nikah laginya?,ayu janda bego pny suami kpn nikah laginya,"[ayu, janda, bego, pny, suami, kpn, nikah, lag..."
9,0,"Anyiennnnggg.. Suaranya ancur banget, lebih me...",anyiennnnggg suaranya ancur banget lebih merdu...,"[anyiennnnggg, suaranya, ancur, banget, lebih,..."

In [42]:
normalized_word = pd.read_csv('kamus_clean.csv')

In [43]:
normalized_word_dict = {}

for index, row in normalized_word.iterrows():
    if row[0] not in normalized_word_dict:
        normalized_word_dict[row[0]] = row[1]

def normalized_term(document):
    return [normalized_word_dict[term] if term in normalized_word_dict else term for term in document]

/tmp/ipython-input-3391283394.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[0] not in normalized_word_dict:
/tmp/ipython-input-3391283394.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  normalized_word_dict[row[0]] = row[1]

In [44]:
df_new['final_tokens'] = df_new['tokens'].apply(normalized_term)

In [45]:
i=0
final_string_tokens = []
for text in df_new['final_tokens'].values:
    EachReviewText = ""
    EachReviewText = ' '.join(text)
    final_string_tokens.append(EachReviewText)

In [46]:
df_new["step02"] = final_string_tokens

In [50]:
df_new.head(100)

,Sentiment,Instagram Comment Text,step01,tokens,final_tokens,step02
0,0,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...,"[username, tolol, gak, ada, hubungan, nya, keg...","[username, tolol, gak, ada, hubungan, nya, keg...",username tolol gak ada hubungan nya keguguran ...
1,0,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tata cowo bgt dibelain balikan hadew...,"[geblek, lo, tata, cowo, bgt, dibelain, balika...","[geblek, lo, tata, cowo, bgt, dibelain, balika...",geblek lo tata cowo bgt dibelain balikan hadew...
2,0,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...,"[kmrn, termewek, skr, lengket, lg, duhhh, kok,...","[kmrn, termewek, skr, lengket, lg, duhhh, kok,...",kmrn termewek skr lengket lg duhhh kok labil b...
3,0,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...,"[intinya, kalau, kesel, dengan, att, nya, gaus...","[intinya, kalau, kesel, dengan, att, nya, gaus...",intinya kalau kesel dengan att nya gausah ke a...
4,0,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lg sakit jiwa knp harus...,"[hadewwwww, permpuan, itu, lg, sakit, jiwa, kn...","[hadewwwww, permpuan, itu, lg, sakit, jiwa, kn...",hadewwwww permpuan itu lg sakit jiwa knp harus...
...,...,...,...,...,...,...
95,0,"Yg nama ny plagiat ya plagiat, walaupun laku t...",yg nama ny plagiat ya plagiat walaupun laku tp...,"[yg, nama, ny, plagiat, ya, plagiat, walaupun,...","[yg, nama, ny, plagiat, ya, plagiat, walaupun,...",yg nama ny plagiat ya plagiat walaupun laku tp...
96,0,"Dasar plagiat semuanya, ga bisa kreatip.memalu...",dasar plagiat semuanya ga bisa kreatip memaluk...,"[dasar, plagiat, semuanya, ga, bisa, kreatip, ...","[dasar, plagiat, semuanya, ga, bisa, kreatip, ...",dasar plagiat semuanya ga bisa kreatip memaluk...
97,0,"Dan dengan begonya dia bilang ""apanya yang sam...",dan dengan begonya dia bilang apanya yang sama...,"[dan, dengan, begonya, dia, bilang, apanya, ya...","[dan, dengan, begonya, dia, bilang, apanya, ya...",dan dengan begonya dia bilang apanya yang sama...
98,0,Itu pacarnya anggel pietrs kali.... dan cowok ...,itu pacarnya anggel pietrs kali dan cowok itu ...,"[itu, pacarnya, anggel, pietrs, kali, dan, cow...","[itu, pacarnya, anggel, pietrs, kali, dan, cow...",itu pacarnya anggel pietrs kali dan cowok itu ...
99,0,"japok gateeel emang,uda jelas dia ada main sam...",japok gateeel emang uda jelas dia ada main sam...,"[japok, gateeel, emang, uda, jelas, dia, ada, ...","[japok, gateeel, emang, uda, jelas, dia, ada, ...",japok gateeel emang uda jelas dia ada main sam...

In [51]:
df_new.to_csv('clean_dataset.csv',sep=";")